### ISSUE TITLE
Ice Drill & Liquefaction Array CFG Fixes

### ISSUE THREAD

**Issue by damianreds** [jbengtson/RealISRU#14]
The Ice Drill is not drilling for ice/water; a change in it's config file is needed:

> RealISRU\Parts\scienceDrill\part.cfg -> Ore to Water

The Licquefaction Array is not licquefying resources; a change in it's config file is needed:

> RealISRU\Parts\MMparts\Refrigerator.cfg -> lqdHydrogen to LqdHydrogen (and same for all resources, i.e. LqdMethane)

The Licquefaction Array is not consuming EC - not fixed in the below updated CFG's.

I have attached the updated CFG files here.

Best regards :)

**Comment by damianreds** [comment]
Don't know how to create a pull request nor attach the updated config files hence pasting them here in the following comments.

1. Ice Drill's CFG;
2. Licquefaction Array CFG.

**Comment by damianreds** [comment]
PART
{
    // --- general parameters ---
    name = **RealISRU_IceDrill**
    module = Part
    author = BahamutoD
    
    // --- asset parameters ---
    mesh = model.mu
    rescaleFactor = .225
    
    // --- node definitions ---
    node_attach = 1.2,  1.2, 0, 1.0, 0, 0.0
    
    // --- editor parameters ---
    cost = 2000
    category = Utility
    subcategory = 0
    title = Ice Drill
    manufacturer = Various
    description = Deployable drill for extracting water from ice and hydrates.  Includes a heating element to separate the liquid water automatically.
    
    TechRequired = advMetalworks
    entryCost = 50
    
    // attachment rules: stack, srfAttach, allowStack, allowSrfAttach, allowCollision
    attachRules = 0,1,0,0,0
    
    mass = 0.25
    dragModelType = default
    maximum_drag = 0.2
    minimum_drag = 0.2
    angularDrag = 2
    crashTolerance = 12
    breakingForce = 200
    breakingTorque = 200
    maxTemp = 5000
    fuelCrossFeed = True
    
    childStageOffset = 1

	MODULE
	{
		name = ModuleResourceHarvester
		HarvesterType = 0
		Efficiency = 0.1
		ResourceName = Water
		ConverterName = Ice Drill
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		ImpactRange = 5
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
		UseSpecialistBonus = false
		
		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = 10
		}
	}

	MODULE
	{
		name = ModuleAsteroidDrill
		DirectAttach = false
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		PowerConsumption = 1
		Efficiency = 0.1
		ImpactRange = 5
		UseSpecialistBonus = false
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
	}





	MODULE
	{
		name = ModuleAnimationGroup
		deployAnimationName = Deploy
		activeAnimationName = Deploy0
		moduleType = Drill
	}

	MODULE
	{
		name = ModuleResourceHarvester
		HarvesterType = 0
		Efficiency = 0.01
		ResourceName = Hydrates
		ConverterName = Ice Drill
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		ImpactRange = 5
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
		UseSpecialistBonus = false
		
		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = 10
		}
	}

	MODULE
	{
		name = ModuleAsteroidDrill
		DirectAttach = false
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		PowerConsumption = 1
		Efficiency = 0.1
		ImpactRange = 5
		UseSpecialistBonus = false
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
	}

	MODULE
	{
		name = ModuleAnimationGroup
		deployAnimationName = Deploy
		activeAnimationName = Deploy0
		moduleType = Drill
	}
}

**Comment by damianreds** [comment]
Ice Drill

```
PART
{
    // --- general parameters ---
    name = RealISRU_IceDrill
    module = Part
    author = BahamutoD
    
    // --- asset parameters ---
    mesh = model.mu
    rescaleFactor = .225
    
    // --- node definitions ---
    node_attach = 1.2,  1.2, 0, 1.0, 0, 0.0
    
    // --- editor parameters ---
    cost = 2000
    category = Utility
    subcategory = 0
    title = Ice Drill
    manufacturer = Various
    description = Deployable drill for extracting water from ice and hydrates.  Includes a heating element to separate the liquid water automatically.
    
    TechRequired = advMetalworks
    entryCost = 50
    
    // attachment rules: stack, srfAttach, allowStack, allowSrfAttach, allowCollision
    attachRules = 0,1,0,0,0
    
    mass = 0.25
    dragModelType = default
    maximum_drag = 0.2
    minimum_drag = 0.2
    angularDrag = 2
    crashTolerance = 12
    breakingForce = 200
    breakingTorque = 200
    maxTemp = 5000
    fuelCrossFeed = True
    
    childStageOffset = 1

	MODULE
	{
		name = ModuleResourceHarvester
		HarvesterType = 0
		Efficiency = 0.1
		ResourceName = Water
		ConverterName = Ice Drill
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		ImpactRange = 5
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
		UseSpecialistBonus = false
		
		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = 10
		}
	}

	MODULE
	{
		name = ModuleAsteroidDrill
		DirectAttach = false
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		PowerConsumption = 1
		Efficiency = 0.1
		ImpactRange = 5
		UseSpecialistBonus = false
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
	}





	MODULE
	{
		name = ModuleAnimationGroup
		deployAnimationName = Deploy
		activeAnimationName = Deploy0
		moduleType = Drill
	}

	MODULE
	{
		name = ModuleResourceHarvester
		HarvesterType = 0
		Efficiency = 0.01
		ResourceName = Hydrates
		ConverterName = Ice Drill
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		ImpactRange = 5
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
		UseSpecialistBonus = false
		
		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = 10
		}
	}

	MODULE
	{
		name = ModuleAsteroidDrill
		DirectAttach = false
		StartActionName = Start Ice Drill
		StopActionName = Stop Ice Drill
		PowerConsumption = 1
		Efficiency = 0.1
		ImpactRange = 5
		UseSpecialistBonus = false
		AutoShutdown = true
		GeneratesHeat = true
        TemperatureModifier = 0.25
	}

	MODULE
	{
		name = ModuleAnimationGroup
		deployAnimationName = Deploy
		activeAnimationName = Deploy0
		moduleType = Drill
	}
}
```

**Comment by damianreds** [comment]
Licquefaction Array

```
+PART[FuelCellArray]
{
    @name = RealISRU_LiquefactionArray

    !MODEL {}
    MODEL
    {
        model = Squad/Parts/Resources/FuelCell/FuelCellArray
        scale = 1.0, 1.0, 1.0
    }
	MODEL
	{
		model = Squad/Parts/Resources/SurfaceScanner/SurfaceScanner
		scale = 1.0, 1.0, 1.0
		position = -0.0863, 0.2941, 0.0
        rotation = 0, 90, 0
	}
	MODEL
	{
		model = Squad/Parts/Science/sensorAccelerometer/model
		scale = 1.0, 1.0, 1.0
		position = -0.06134, 0.72369, 0.0
        rotation = 0, 90, 0
	}
	MODEL
	{
		model = Squad/Parts/Science/sensorAccelerometer/model
		scale = 1.0, 1.0, 1.0
		position = -0.06354, -0.10946, 0.0
        rotation = 0, 90, 0
	}

    @node_attach = .05, 0, 0, 1, 0, 0, 0

    @TechRequired = specializedElectrics
    @entryCost = 13500
    @cost = 4500
    @category = Utility
    @subcategory = 0
    @title = Liquefaction Array
    @manufacturer = Various
    @description = Uses a combination of active cooling and pressurization turbines to convert gasses into liquids.
    @attachRules = 0,1,0,0,0

    // --- standard part parameters ---
    @mass = 0.75
    @dragModelType = default
    @maximum_drag = 0.2
    @minimum_drag = 0.2
    @angularDrag = 2
    @crashTolerance = 7
    @maxTemp = 2000 // = 3000

	!MODULE[ModuleResourceConverter] {}
	!RESOURCE[ElectricCharge] {}

    MODULE
    {
        name = ModuleResourceConverter
        ConverterName = Liquefy Oxygen
        StartActionName = Start Liquefying Oxygen
        StopActionName = Stop Liquefying Oxygen
        AutoShutdown = false
        GeneratesHeat = true
        UseSpecialistBonus = false

        INPUT_RESOURCE
        {
            ResourceName = Oxygen
            Ratio = 1
        }
        OUTPUT_RESOURCE
        {
            ResourceName = LqdOxygen
            Ratio = 0.00247157800561483
            DumpExcess = false
        }
    }

    MODULE
    {
        name = ModuleResourceConverter
        ConverterName = Liquefy Hydrogen
        StartActionName = Start Liquefying Hydrogen
        StopActionName = Stop Liquefying Hydrogen
        AutoShutdown = false
        GeneratesHeat = true
        UseSpecialistBonus = false

        INPUT_RESOURCE
        {
            ResourceName = Hydrogen
            Ratio = 1
        }
        OUTPUT_RESOURCE
        {
            ResourceName = LqdHydrogen
            Ratio = 0.00253785653674714
            DumpExcess = false
        }
    }

    MODULE
    {
        name = ModuleResourceConverter
        ConverterName = Liquefy Ammonia
        StartActionName = Start Liquefying Ammonia
        StopActionName = Stop Liquefying Ammonia
        AutoShutdown = false
        GeneratesHeat = true
        UseSpecialistBonus = false

        INPUT_RESOURCE
        {
            ResourceName = Ammonia
            Ratio = 1
        }
        OUTPUT_RESOURCE
        {
            ResourceName = LqdAmmonia
            Ratio = 0.00109525470243689
            DumpExcess = false
        }
    }

    MODULE
    {
        name = ModuleResourceConverter
        ConverterName = Liquefy Methane
        StartActionName = Start Liquefying Methane
        StopActionName = Stop Liquefying Methane
        AutoShutdown = false
        GeneratesHeat = true
        UseSpecialistBonus = false

        INPUT_RESOURCE
        {
            ResourceName = Methane
            Ratio = 1
        }
        OUTPUT_RESOURCE
        {
            ResourceName = LqdMethanee
            Ratio = 0.00168489923601513
            DumpExcess = false
        }
    }
}

```

**Comment by stratochief66** [comment]
@damianreds if you're interested in learning the basics of Github PR's (Pull Requests) hopefully this helps.

So, I copy and pasted the text from your first comment with the MM code for the Ice Drill into a file called part.cfg

I then navigated to where that file is found in the Repo, here:
https://github.com/jbengtson/RealISRU/tree/master/GameData/RealISRU/Parts/scienceDrill

Next, I dragged and dropped my local part.cfg in there (from my Windows file system to my Chrome browser), and created a new 'branch' (copy of the repository that contains my (your) changes)

I then wrote in the one line description of that branch (Example for demo'ing PR #15)

And finally, put this Issue number into the next section. (#14) Normally that section would/could contain a longer form version of the changes being made or even a general description is handy.

If you want to give that a go, feel free. My example PR won't cause you any harm, and you trying to make a PR can't possibly hurt anything. :)

If you'd prefer not to make the attempt, just let me know.

**Comment by damianreds** [comment]
@stratochief66 OMG so sorry I completely missed your reply - again I'm a total noob @ github and never noticed the 'notification'
I am currently swamped with RL so I can't say I will be able to create the Pull Request - would you mind taking my changes yourself?
