### ISSUE TITLE
Mars CO2 Intake size.

### ISSUE THREAD

**Issue by Bornholio** [jbengtson/RealISRU#19]
Is the intake part intended to be sized the same as the other "Hexcore" large size parts?
The three CO2 intakes are all small, about universal storage sized.
http://imgur.com/7PDihbx

**Comment by Bornholio** [comment]
in Mars_ISRU.cfg

 remove lines 169-171
`	@attachRules = 0,1,0,0,0
	
%rescaleFactor = 0.3`

Result is part appearing and mounting same as the other Hex parts
http://imgur.com/Up2GbTV

**Comment by stratochief66** [comment]
Yep, I just stole the model to use as a WIP part representation. If you find a more appropriate model, or want to do some search and see what size they should actually be, feel free. :)

**Comment by Bornholio** [comment]
closed by #22
