### ISSUE TITLE
Needs system wide search tag

### ISSUE THREAD

**Issue by Bornholio** [jbengtson/RealISRU#20]
Needs a Tag that is unique and collects all Real ISRU parts, 
I'd suggest MARS, INSITU and REALISRU

**Comment by Bornholio** [comment]
/master/GameData/RealISRU/Parts/HexAssembly/HaberBosch.cfg
after line 32
```
bulkheadProfiles = Hexcore
tags = conver isru mine mining process resource MARS INSITU REALISRU
```
as an example
could simplify to just 
`tags = MARS INSITU REALISRU`
and bulk add to all parts allowing quit search to bring up part set

**Comment by stratochief66** [comment]
sounds reasonable.

**Comment by Bornholio** [comment]
I'll start doing that in my branch and PR it once its ready

**Comment by Bornholio** [comment]
submitted PR #22
