### ISSUE TITLE
DumpExcess = False

### ISSUE THREAD

**Issue by Starwaster** [jbengtson/RealISRU#25]
Setting DumpExcess = False is fine on a generator with a solitary output and you don't want it running unnecessarily but it's not really appropriate for ISRU where you have a lot of interlinked resource inputs/outputs and some might be necessary for another ISRU process or it might not be. Case in point: trying to run a Sabatier for methane production but there's no room for the water that I don't really need so the process will fail outright.  And it HAS to fail everytime unless you have a consumer that is using the water as fast or faster than it can be produced.

I've been doing some work on it and will likely do a pull request though I have to wonder if this is even being used? Did it ever see any serious player usage? Is there no point to me doing a pull request?

**Comment by Bornholio** [comment]
I'd love if it got a real release. I've had plenty of questions directed to it.  Pap, Egg, PF or RN could push a PR or release easily I think.  Stratochief didn't feel involved enough to push my PR's.

**Comment by Starwaster** [comment]
Fixed this with PR #26
