### ISSUE TITLE
Temp Part Patch for Starwasters Fork 

### ISSUE THREAD

**Issue by Bornholio** [jbengtson/RealISRU#30]
https://github.com/Starwaster/RealISRU

part patch for testing in RP1

https://github.com/Bornholio/RealISRU/blob/master/TREE_REALISRU.cfg

**Comment by basilatrue** [comment]
```
[ERR 20:32:15.163] [ModuleManager] Error - node name does not have balanced brackets (or a space - if so replace with ?):
RealISRU/TREE_REALISRU/@PART[RealISRU_Hex_Core_Pass

[ERR 20:32:15.166] [ModuleManager] Error - node name does not have balanced brackets (or a space - if so replace with ?):
RealISRU/TREE_REALISRU/@PART[KA_Drill_Radial_04
```
i noticed odd spaces in TREE_REALISRU.cfg

**Comment by Starwaster** [comment]
sorry, not seeing it, can you highlight a line in the config demonstrating?

**Comment by Bornholio** [comment]
fixed it, was extra spaces in the names of two parts

**Comment by Starwaster** [comment]
FYI I nuked my personal branch so that I can better ensure that updates from me go directly to this branch

**Comment by Starwaster** [comment]
and I think this issue is already resolved isn't it? Closing it.

**Comment by Bornholio** [comment]
sure, there is a copy in a place holder PR on RP0
https://github.com/KSP-RO/RP-0/blob/f7b3f49f093ec5c0556d616b38ddb28a8017c025/GameData/RP-0/Tree/TREE_REALISRU.cfg
