### ISSUE TITLE
Liquefaction array doesn't work

### ISSUE THREAD

**Issue by pradyjowski** [jbengtson/RealISRU#7]
Click on "Start liquefying Oxygen/Hydrogen/Ammonia/Methane", appropriate indication says "Operational " and nothing happens. Proper resources and storage space are provided (otherwise I'd get proper message in the indicator).
When operational the debug consol is spammed with:
[Exception]: NullReferenceException: Object reference not set to an instance of an object 

My Install
KSP 1.0.5 Linux 64bit
Realism overhaul installed through CKAN (can provide full mod list upon request)

Let me know what else can I provide to help.

BTW. Love the mod idea mod and keep my fingers crossed!

**Comment by Max-Q** [comment]
I think the error was that the output resource was written without a capital letter (lqd* and not Lqd*)

**Comment by stratochief66** [comment]
Looks like this is corrected by your PR @Max-Q , #18 

Thanks!
